[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile"
watchPatterns = ["apps/api/**", "apps/walkin/package.json", "packages/**", "package.json", "package-lock.json", "railway.toml"]


[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
